### ISSUE TITLE
week 5 is complete

### ISSUE THREAD

**Issue by skotcharat** [skotcharat/doforfund#4]
@pawaitemadisoncollege week 5 is complete

**Comment by pawaitemadisoncollege** [comment]
Excellent work implementing the generic dao already!

- [x] Should this be insertWithRoleSuccess instead? https://github.com/skotcharat/doforfund/blob/89e3c18d944bfabbbf59977abc5fbaa981b36980/src/test/java/edu/matc/persistence/UserDaoTest.java#L90
- [x] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually.
